### ISSUE TITLE
disqus.js was not copied into static folder

### ISSUE THREAD

**Issue by gtalarico** [Robpol86/sphinxcontrib-disqus#5]
make command is running find, and the code is getting inject into the html.
the disqus.js file however, is not showing anywhere.

![image](https://cloud.githubusercontent.com/assets/9513968/24834075/fe816bde-1ca8-11e7-9bc6-076b0442d117.png)

This is my repo
https://github.com/gtalarico/revitpythonwrapper

Thanks for the great pkg!

**Comment by gtalarico** [comment]
Fixed by making my own `disqus.js` with universalcode from admin page.

**Comment by Robpol86** [comment]
Hmm, seems like if you comment out `html_static_path = ['_static']` in https://github.com/gtalarico/revitpythonwrapper/blob/master/docs/conf.py#L183 the file is copied over. That's the default directory so that should be a quick fix for you.

I feel like this may still be a bug in this extension. I'll look into handling this case so that people with custom static folder names can still use my extension.

Thanks for reporting this!

**Comment by dominicpace** [comment]
Commenting out `html_static_path = ['_static']` did not work. I had to create my own `disqus.js` file and include it in my `_static` folder like @gtalarico suggested to get Disqus working.

**Comment by Robpol86** [comment]
No longer able to reproduce, even with the old version of Sphinx and pip installing your requirements file from 2017. Reopen if this is still an issue.
